# Generated by Django 4.2 on 2023-05-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_contact_pnumbner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pnumbner',
            field=models.CharField(max_length=12),
        ),
    ]
