# Generated by Django 4.2 on 2023-05-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_enrollment_amount_enrollment_duedate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tital', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='gallary')),
                ('timeStamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
