# Generated by Django 4.2 on 2023-05-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_gallary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='img',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
