# Generated by Django 4.2 on 2023-05-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_gallary_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selsectdate', models.DateField(auto_now_add=True)),
                ('login', models.CharField(max_length=200)),
                ('logout', models.CharField(max_length=200)),
                ('selectworkout', models.CharField(max_length=200)),
                ('trainedby', models.CharField(max_length=200)),
            ],
        ),
    ]
