# Generated by Django 4.2 on 2023-05-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
