# Generated by Django 4.2 on 2023-05-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_attendence_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='PhoneNumber',
            new_name='phonenumber',
        ),
    ]
