# Generated by Django 4.2 on 2023-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_rename_phonenumber_attendence_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=100)),
                ('simg', models.ImageField(upload_to='serviceimg')),
            ],
        ),
    ]
