# Generated by Django 4.2 on 2023-05-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
