# Generated by Django 4.2 on 2023-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_services_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
