# Generated by Django 4.2 on 2023-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_alter_enrollment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutname', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('simg', models.ImageField(upload_to='workout')),
            ],
        ),
    ]
