# Generated by Django 4.2 on 2023-05-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='about',
        ),
        migrations.AddField(
            model_name='workout',
            name='numberofset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='repitaions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='workouttype',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
